from abc import abstractmethod
from beers_utils.abstract_pipeline_step import AbstractPipelineStep

class AbstractBeersPipeline(AbstractPipelineStep):
    """
    Abstract class defining the minimal methods required by a BEERS2 pipeline.

    The job-monitoring framework defined in BEERS_UTILS is designed to package
    jobs using AbstractPipelineStep objects (or its implementations). BEERS2
    interacts with a job submission framework a little differently, as it is
    designed to submit an entire pipeline to a job scheduler. An individual
    step in this pipeline directly submits its output to the next step
    without writing any data to an intermediate file on disk. As a result,
    this entire pipeline is executed in serial, though the overall BEERS2 run
    is broken up into several of these pipeline submissions.

    So in this context, a BEERS2 pipeline consists of a series of steps that
    will be executed serially. The instance of the pipeline will be submitted
    to the job handling framework defined in BEERS_UTILS, which will submit
    the pipeline to run using whichever job scheduler the user defines.

    """

    @abstractmethod
    def execute(self):
        """
        Entry point into the BEERS2 pipeline.
        """
        pass

    @abstractmethod
    def validate(self):
        """
        Checks validity of parameters used to instantiate the BEERS2 pipeline.

        Returns
        -------
        boolean
            True  - All parameters required to run this pipeline were provided and
                    are within valid ranges.
            False - One or more of the paramters is missing or contains an invalid
                    value.
        """
        pass

    @abstractmethod
    def get_commandline_call(self):
        """
        Prepare command to execute the pipeline from the command line, given all of
        the parameters used to call the execute() method.

        Parameters
        ----------
        The same or equivalent parameters given to the execute() method.

        Returns
        -------
        string
            Command to execute on the command line. It will perform the same
            operations as a call to execute() with the same parameters.

        """
        pass

    @abstractmethod
    def get_validation_attributes(self):
        """
        Prepare attributes required by the is_output_valid() method to validate
        output generated by executing this specific instance of the pipeline
        (either through the command line call or the execute method).

        Returns
        -------
        dict
            Key-value pairings of attributes accepted by the is_output_valid()
            method.

        """
        pass

    @staticmethod
    @abstractmethod
    def is_output_valid(validation_attributes):
        """
        Check if output of this pipeline, for a specific job/execution is correctly
        formed and valid, given the dictionary of validation attributes. Prepare
        these attributes for a given executing by calling the get_validation_attributes()
        method.

        Parameters
        ----------
        validation_attributes : dict
            Key-value pairings of attributes generated by the get_validation_attributes()
            method.

        Returns
        -------
        boolean
            True  - Output files for this pipeline were created and are well formed.
            False - Output files for this pipeline do not exist or are missing data.
        """
        pass

    @staticmethod
    @abstractmethod
    def main():
        """
        Entry point into script. Allows script to be executed/submitted via the
        command line.
        """
        pass
