import sys
import re
from timeit import default_timer as timer
import numpy as np
from beers_utils.molecule import Molecule

class RiboZeroStep:
    """
    This step simulates the RiboZero procedure, which uses a library of oligos to deplete the ribosomal rRNA
    content of the sample.

    The library of oligos is sourced from:
        Adiconis, X., Borges-Rivera, D., Satija, R. et al.
        Comparative analysis of RNA sequencing methods for degraded or low-input samples.
        Nat Methods 10, 623-629 (2013). https://doi.org/10.1038/nmeth.2483

    Configuration Example::

        # Chance to degrade a molecule that matches one of the oligos
        match_degrade_chance: 0.99

        # If true, degrade/remove the entire molecule if any part matches
        # otherwise, fragments the molecule around the match and removes
        # the matching segment.
        degrade_entire_molecule: False
    """

    name = "RiboZero Step"

    def __init__(self, parameters, global_config):
        self.match_degrade_chance = parameters["match_degrade_chance"]
        self.degrade_entire_molecule = parameters["degrade_entire_molecule"]
        self.global_config = global_config
        print("RiboZero selection step instantiated")

        # The regular expression that matches to any of the oligos
        # in the oligo library. Looks for exact matches only
        self.oligo_match_re = re.compile("|".join(OLIGO_LIBRARY))

    def execute(self, molecule_packet, rng, log):
        print("RiboZero selection step starting")
        retained_molecules = []
        for molecule in molecule_packet.molecules:
            # Check if any of the oligo sequences are present in the molecule
            matches = self.oligo_match_re.finditer(molecule.sequence)
            times_degraded = 0
            remaining_molecule = molecule
            last_end = 1
            for match in matches:
                degraded = (rng.random() <= self.match_degrade_chance)

                if not degraded:
                    continue
                times_degraded += 1

                if self.degrade_entire_molecule:
                    # Don't retain any of the molecule
                    continue

                # Retain the piece between the end of the last fragment and this oligo match
                start, end = match.span()
                new_mol = molecule.make_fragment(last_end, start)
                if len(new_mol.sequence) > 0:
                    retained_molecules.append(new_mol)

                last_end = end + 1
            if times_degraded > 0:
                note = f'degraded {times_degraded} times'

                if not self.degrade_entire_molecule:
                    # Take the piece after the last oligo match
                    new_mol = molecule.make_fragment(last_end, len(molecule.sequence))
                    if len(new_mol.sequence) > 0:
                        retained_molecules.append(new_mol)
            else:
                retained_molecules.append(molecule)
                note = 'retained'
            log.write(molecule, note)
        print("RiboZero selection step complete")
        molecule_packet.molecules = retained_molecules
        return molecule_packet

    @staticmethod
    def validate(parameters, global_config):
        errors = []
        if "match_degrade_chance" in parameters:
            match_degrade_chance = parameters["match_degrade_chance"]
            if match_degrade_chance < 0 or min_retention_prob > 1:
                errors.append("The match degradation chance (match_degrade_chance) must be between 0 and 1")
        else:
            errors.append("Must specify match_degrade_chance (between 0 and 1)")
        if "degrade_entire_molecule" in parameters:
            degrade_entire_molecule = parameters["degrade_entire_molecule"]
            if degrade_entire_molecule not in [True, False]:
                errors.append("degrade_entire_molecule must be a boolean value")
        else:
            errors.append("Must specify degrade_entire_molecule (boolean)")
        return errors

OLIGO_LIBRARY = """
TAATGATCCTTCCGCAGGTTCACCTACGGAAACCTTGTTACGACTTTTAC
TTCCTCTAGATAGTCAAGTTCGACCGTCTTCTCAGCGCTCCGCCAGGGCC
GTGGGCCGACCCCGGCGGGGCCGATCCGAGGGCCTCACTAAACCATCCAA
TCGGTAGTAGCGACGGGCGGTGTGTACAAAGGGCAGGGACTTAATCAACG
CAAGCTTATGACCCGCACTTACTCGGGAATTCCCTCGTTCATGGGGAATA
ATTGCAATCCCCGATCCCCATCACGAATGGGGTTCAACGGGTTACCCGCG
CCTGCCGGCGTAGGGTAGGCACACGCTGAGCCAGTCAGTGTAGCGCGCGT
GCAGCCCCGGACATCTAAGGGCATCACAGACCTGTTATTGCTCAATCTCG
GGTGGCTGAACGCCACTTGTCCCTCTAAGAAGTTGGGGGACGCCGACCGC
TCGGGGGTCGCGTAACTAGTTAGCATGCCAGAGTCTCGTTCGTTATCGGA
ATTAACCAGACAAATCGCTCCACCAACTAAGAACGGCCATGCACCACCAC
CCACGGAATCGAGAAAGAGCTATCAATCTGTCAATCCTGTCCGTGTCCGG
GCCGGGTGAGGTTTCCCGTGTTGAGTCAAATTAAGCCGCAGGCTCCACTC
CTGGTGGTGCCCTTCCGTCAATTCCTTTAAGTTTCAGCTTTGCAACCATA
CTCCCCCCGGAACCCAAAGACTTTGGTTTCCCGGAAGCTGCCCGGCGGGT
CATGGGAATAACGCCGCCGCATCGCCGGTCGGCATCGTTTATGGTCGGAA
CTACGACGGTATCTGATCGTCTTCGAACCTCCGACTTTCGTTCTTGATTA
ATGAAAACATTCTTGGCAAATGCTTTCGCTCTGGTCCGTCTTGCGCCGGT
CCAAGAATTTCACCTCTAGCGGCGCAATACGAATGCCCCCGGCCGTCCCT
CTTAATCATGGCCTCAGTTCCGAAAACCAACAAAATAGAACCGCGGTCCT
ATTCCATTATTCCTAGCTGCGGTATCCAGGCGGCTCGGGCCTGCTTTGAA
CACTCTAATTTTTTCAAAGTAAACGCTTCGGGCCCCGCGGGACACTCAGC
TAAGAGCATCGAGGGGGCGCCGAGAGGCAAGGGGCGGGGACGGGCGGTGG
CTCGCCTCGCGGCGGACCGCCCGCCCGCTCCCAAGATCCAACTACGAGCT
TTTTAACTGCAGCAACTTTAATATACGCTATTGGAGCTGGAATTACCGCG
GCTGCTGGCACCAGACTTGCCCTCCAATGGATCCTCGTTAAAGGATTTAA
AGTGGACTCATTCCAATTACAGGGCCTCGAAAGAGTCCTGTATTGTTATT
TTTCGTCACTACCTCCCCGGGTCGGGAGTGGGTAATTTGCGCGCCTGCTG
CCTTCCTTGGATGTGGTAGCCGTTTCTCAGGCTCCCTCTCCGGAATCGAA
CCCTGATTCCCCGTCACCCGTGGTCACCATGGTAGGCACGGCGACTACCA
TCGAAAGTTGATAGGGCAGACGTTCGAATGGGTCGTCGCCGCCACGGG
GCGTGCGATCGGCCCGAGGTTATCTAGAGTCACCAAAGCCGCCGGCGCCC
GCCCCCCGGCCGGGGCCGGAGAGGGGCTGACCGGGTTGGTTTTGATCTGA
TAAATGCACGCATCCCCCCCGCGAAGGGGGTCAGCGCCCGTCGGCATGTA
TTAGCTCTAGAATTACCACAGTTATCCAAGTAGGAGAGGAGCGAGCGACC
AAAGGAACCATAACTGATTTAATGAGCCATTCGCAGTTTCACTGTACCGG
CCGTGCGTACTTAGACATGCATGGCTTAATCTTTGAGACAAGCATATGCT
TGGCTTAATCTTTGAGACAAGCATATGCTACTGGCAGGATCAACCAGGTA
GACAAACCCTTGTGTCGAGGGCTGACTTTCAATAGATCGCAGCGAGGGAG
CTGCTCTGCTACGTACGAAACCCCGACCCAGAAGCAGGTCGTCTACGAAT
GGTTTAGCGCCAGGTTCCCCACGAACGTGCGGTGCGTGACGGGCGAGGG
GCGGCCGCCTTTCCGGCCGCGCCCCGTTTCCCAGGACGAAGGGCACTCCG
CACCGGACCCCGGTCCCGGCGCGCGGCGGGGCACGCGCCCTCCCGCGGCG
GGGCGCGTGGAGGGGIGGGCGGCCCGCCGGCGGGGACAGGCGGGGGACCG
GCTATCCGAGGCCAACCGAGGCTCCGCGGCGCTGCCGTATCGTTCGCCTG
GGCGGGATTCTGACTTAGAGGCGTTCAGTCATAATCCCACAGATGGTAGC
TTCGCCCCATTGGCTCCTCAGCCAAGCACATACACCAAATGTCTGAACCT
GCGGTTCCTCTCGTACTGAGCAGGATTACCATGGCAACAACACATCATCA
GTAGGGTAAAACTAACCTGTCTCACGACGGTCTAAACCCAGCTCACGTTC
CCTATTAGTGGGTGAACAATCCAACGCTTGGCGAATTCTGCTTCACAATG
ATAGGAAGAGCCGACATCGAAGGATCAAAAAGCGACGTCGCTATGAACGC
TTGGCCGCCACAAGCCAGTTATCCCTGTGGTAACTTTTCTGACACCTCCT
GCTTAAAACCCAAAAGGTCAGAAGGATCGTGAGGCCCCGCTTTCACGGTC
TGTATTCGTACTGAAAATCAAGATCAAGCGAGCTTTTGCCCTTCTGCTCC
ACGGGAGGTTTCTGTCCTCCCTGAGCTCGCCTTAGGACACCTGCGTTACC
GTTTGACAGGTGTACCGCCCCAGTCAAACTCCCCACCTGGCACTGTCCCC
GGAGCGGGTCGCGCCCGGCCGGGCGGGCGCTTGGCGCCAGAAGCGAGAGC
CCCTCGGGCTCGCCCCCCCGCCTCACCGGGTCAGTGAAAAAACGATCAGA
GTAGTGGTATTTCACCGGCGGCCCGCAGGGCCGCGGACCCCGCCCCGGGC
CCCTCGCGGGGACACCGGGIGGGCGCCGGGGGCCTCCCACTTATTCTACA
CCTCTCATGTCTCTTCACCGTGCCAGACTAGAGTCAAGCTCAACAGGGTC
TTCTTTCCCCGCTGATTCCGCCAAGCCCGTTCCCTTGGCTGTGGTTTCGC
TGGATAGTAGGTAGGGACAGTGGGAATCTCGTTCATCCATTCATGCGCGT
CACTAATTAGATGACGAGGCATTTGGCTACCTTAAGAGAGTCATAGTTAC
TCCCGCCGTTTACCCGCGCTTCATTGAATTTCTTCACTTTGACATTCAGA
GCACTGGGCAGAAATCACATCGCGTCAACACCCGCCGCGGGCCTTCGCGA
TGCTTTGTTTTAATTAAACAGTCGGATTCCCCTGGTCCGCACCAGTTCTA
AGTCGGCTGCTAGGCGCCGGCCGAGGCGAGGCGCGCGCGGAACCGCGGCC
CCGGGGGCGGACCCGGCGGGIGGGACCGGCCCGCGGCCCCTCCGCCGCCT
GCCGCCGCCGCCGCCGCGCGCCGAGGAGGAGGGGGGAACGGGGGGCGGAC
GGGCCGGGIGGGTAGGGCGGGGGGACGAACCGCCCCGCCCCGCCGCCCG
CCGACCGCCGCCGCCCGACCGCTCCCGCCCCCAGCGGACGCGCGCGCGAC
CGAGACGTGGGGTGGGGGTGGGGGGCGCGCCGCGCCGCCGCCGGGCTCCC
CGGGGGCGGCCGCGACGCCCGCCGCAGCTGGGGCGATCCACGGGAAGGGC
CCGGCTCGCGTCCAGAGTCCGCGCCGCCGCCGGCCCCCCGGGTCCCCGGG
GCCCCCCTCGCGGGGACCTGCCCCCGCCGGCCGCCCCGGCGGCCGCCGCG
CGGCCCCTGCCGCCCCGACCCTTCTCCCCCCGCCGCGCCCCCACGCGGCG
CTCCCCCGGGGAGGGGGGAGGACGGGGAGCGGGGGAGAGAGAGAGAGAGA
GGGCGCGGGGTGGGGAGGGAGCGAGCGGCGCGCGCGGGTGGGGCGGGGGA
GGGCCGCGAGGGGGGTGCCCCGGGCGTGGGGIGGGCGCGCGCCTCGTCCA
GCCGCGGCGCGCGCCCAGCCCCGCTTCGCGCCCCAGCCCGACCGACCCAG
CCCTTAGAGCCAATCCTTATCCCGAAGTTACGGATCCGGCTTGCCGACTT
CCCTTACCTACATTGTTCCAACATGCCAGAGGCTGTTCACCTTGGAGACC
TGCTGCGGATATGGGTACGGCCCGGCGCGAGATTTACACCCTCTCCCCCG
GATTTTCAAGGGCCAGCGAGAGCTCACCGGACGCCGCCGGAACCGCGACG
CTTTCCAAGGCACGGGCCCCTCTCTCGGGGCGAACCCATTCCAGGGCGCC
CTGCCCTTCACAAAGAAAAGAGAACTCTCCCCGGGGCTCCCGCCGGCTTC
TCCGGGATCGGTCGCGTTACCGCACTGGACGCCTCGCGGCGCCCATCTCC
GCCACTCCGGATTCGGGGATCTGAACCCGACTCCCTTTCGATCGGCCGAG
GGCAACGGAGGCCATCGCCCGTCCCTTCGGAACGGCGCTCGCCCATCTCT
CAGGACCGACTGACCCATGTTCAACTGCTGTTCACATGGAACCCTTCTCC
ACTTCGGCCTTCAAAGTTCTCGTTTGAATATTTGCTACTACCACCAAGAT
CTGCACCTGCGGCGGCTCCACCCGGGCCCGCGCCCTAGGCTTCAAGGCTC
ACCGCAGCGGCCCTCCTACTCGTCGCGGCGTAGCGTCCGCGGGGCTCCGG
GGGCGGGGAGCGGGGCGTGGGCGGGAGGAGGGGAGGAGGCGTGGG
GGGCGGGGGAAGGACCCCACACCCCCGCCGCCGCCGCCGCCGCCGCCCTC
CGACGCACACCACACGCGCGCGCGCGCGCGCCGCCCCCGCCGCTCCCGTC
CACTCTCGACTGCCGGCGACGGCCGGGTATGGGCCCGACGCTCCAGCGCC
ATCCATTTTCAGGGCTAGTTGATTCGGCAGGTGAGTTGTTACACACTCCT
TAGCGGATTCCGACTTCCATGGCCACCGTCCTGCTGTCTATATCAACCAA
CACCTTTTCTGGGGTCTGATGAGCGTCGGCATCGGGCGCCTTAACCCGGC
GTTCGGTTCATCCCGCAGCGCCAGTTCTGCTTACCAAAAGTGGCCCACTA
GGCACTCGCATTCCACGCCCGGCTCCACGCCAGCGAGCCGGGCTTCTTAC
CCATTTAAAGTTTGAGAATAGGTTGAGATCGTTTCGGCCCCAAGACCTCT
AATCATTCGCTTTACCGGATAAAACTGCGTGGCGGGGGTGCGTCGGGTCT
GCGAGAGCGCCAGCTATCCTGAGGGAAACTTCGGAGGGAACCAGCTACTA
GATGGTTCGATTAGTCTTTCGCCCCTATACCCAGGTCGGACGACCGATTT
GCACGTCAGGACCGCTACGGACCTCCACCAGAGTTTCCTCTGGCTTCGCC
CTGCCCAGGCATAGTTCACCATCTTTCGGGTCCTAACACGTGCGCTCGTG
CTCCACCTCCCCGGCGCGGCGGGCGAGACGGGCCGGTGGTGCGCCCTCGG
CGGACTGGAGAGGCCTCGGGATCCCACCTCGGCCGGCGAGCGCGCCGGCC
TTCACCTTCATTGCGCCACGGCGGCTTTCGTGCGAGCCCCCGACTCGCGC
ACGTGTTAGACTCCTTGGTCCGTGTTTCAAGACGGGTCGGGTGGGTAGCC
GACGTCGCCGCCGACCCCGTGCGCTCGCTCCGCCGTCCCCCTCTTCGGG
GACGCGCGCGTGGCCCCGAGAGAACCTCCCCCGGGCCCGACGGCGCGACC
CGCCCGGGGCGCACTGGGGACAGTCCGCCCCGCCCCCCGACCCGCGCGCG
GCACCCCCCCCGTCGCCGGGGCGGGGGCGCGGGGAGGAGGGGTGGGAGAG
CGGTCGCGCCGTGGGAGGGGTGGCCCGGCCCCCCCACGAGGAGACGCCGG
CGCGCCCCCGCGGGGGAGACCCCCCTCGCGGGGGATTCCCCGCGGGGGTG
GGCGCCGGGAGGGGGGAGAGCGCGGCGACGGGTCTCGCTCCCTCGGCCCC
GGGATTCGGCGAGTGCTGCTGCCGGGGGGGCTGTAACACTCGGGGIGGGT
TTCGGTCCCGCCGCCCCCGCCGCCGCCGCCACCGCCGCCGCCGCCGCCGC
CCCGACCCGCGCGCCCTCCCGAGGGAGGACGCGGGGCCGGGGGGCGGAGA
CGGGGGAGGAGGAGGACGGACGGACGGACGGGGCCCCCCGAGCCACCTTC
CCCGCCGGGCCTTCCCAGCCGTCCCGGAGCCGGTCGCGGCGCACCGCCGC
GGTGGAAATGCGCCCGGCGGCGGCCGGTCGCCGGTCGGGGGACGGTCCCC
CGCCGACCCCACCCCCGGCCCCGCCCGCCCACCCCCGCACCCGCCGGAGC
CCGCCCCCTCCGGGGAGGAGGAGGAGGGGCGGCGGGGGAAGGGAGGGCGG
GTGGAGGGGTCGGGAGGAACGGGGGGCGGGAAAGATCCGCCGGGCCGCCG
ACACGGCCGGACCCGCCGCCGGGTTGAATCCTCCGGGCGGACTGCGCGGA
CCCCACCCGTTTACCTCTTAACGGTTTCACGCCCTCTTGAACTCTCTCTT
CAAAGTTCTTTTCAACTTTCCCTTACGGTACTTGTTGACTATCGGTCTCG
TGCCGGTATTTAGCCTTAGATGGAGTTTACCACCCGCTTTGGGCTGCATT
CCCAAGCAACCCGACTCCGGGAAGACCCGGGCGCGCGCCGGCCGCTACCG
GCCTCACACCGTCCACGGGCTGGGCCTCGATCAGAAGGACTTGGGCCCCC
CACGAGCGGCGCCGGGGAGCGGGTCTTCCGTACGCCACATGTCCCGCGCC
CCGCGGGGCGGGGATTCGGCGCTGGGCTCTTCCCTGTTCACTCGCCGTTA
CTGAGGGAATCCTGGTTAGTTTCTTTTCCTCCGCTGACTAATATGCTTAA
GACTAATATGCTTAAATTCAGCGGGTCGCCACGTCTGATCTGAGGTCGCG
AAGCGACGCTCAGACAGGCGTAGCCCCGGGAGGAACCCGGGGCCGCAAGT
GCGTTCGAAGTGTCGATGATCAATGTGTCCTGCAATTCACATTAATTCTC
GCAGCTAGCTGCGTTCTTCATCGACGCACGAGCCGAGTGATCCACCGCTA
AAACCCTGTTCTTGGGTGGGTGTGGGTATAATACTAAGTTGAGATGATAT
CATTTACGGGGGAAGGCGCTTTGTGAAGTAGGCCTTATTTCTCTTGTCCT
TTCGTACAGGGAGGAATTTGAANGTAGATAGAAACCGACCTGGATTACTC
CGGTCTGAACTCAGATCACGTAGGACTTTAATCGTTGAACAAACGAACCT
TTAATAGCGGCTGCACCATCGGGATGTCCTGATCCAACATCGAGGTCGTA
AACCCTATTGTTGATATGGACTCTAGAATAGGATTGCGCTGTTATCCCTA
GGGTAACTTGTTCCGTTGGTCAAGTTATTGGATCAATTGAGTATAGTAGT
TCGCTTTGACTGGTGAAGTCTTAGCATGTACTGCTCGGAGGTTGGGTTCT
GCTCCGAGGTCGCCCCAACCGAAATTTTTAATGCAGGTTTGGTAGTTTAG
GACCTGTGGGTTTGTTAGGTACTGTTTGCATTAATAAATTAAAGCTCCAT
AGGGTCTTCTCGTCTTGCTGTGTTATGCCCGCCTCTTCACGGGCAGGTCA
ATTTCACTGGTTAAAAGTAAGAGACAGCTGAACCCTCGTGGAGCCATTCA
TACAGGTCCCTATTTAAGGAACAAGTGATTATGCTACCTTTGCACGGTTA
GGGTACCGCGGCCGTTAAACATGTGTCACTGGGCAGGCGGTGCCTCTAAT
ACTGGTGATGCTAGAGGTGATGTTTTTGGTAAACAGGCGGGGTAAGATTT
GCCGAGTTCCTTTTACTTTTTTTAACCTTTCCTTATGAGCATGCCTGTGT
TGGGTTGACAGTGAGGGTAATAATGACTTGTTGGTTGATTGTAGATATTG
GGCTGTTAATTGTCAGTTCAGTGTTTTAATCTGACGCAGGCTTATGCGGA
GGAGAATGTTTTCATGTTACTTATACTAACATTAGTTCTTCTATAGGGTG
ATAGATTGGTCCAATTGGGTGTGAGGAGTTCAGTTATATGTTTGGGATTT
TTTAGGTAGTGGGTGTTGAGCTTGAACGCTTTCTTAATTGGTGGCTGCTT
TTAGGCCTACTATGGGTGTTAAATTTTTTACTCTCTCTACAAGGTTTTTT
CCTAGTGTCCAAAGAGCTGTTCCTCTTTGGACTAACAGTTAAATTTACAA
GGGATTTAGAGGGTTCTGTGGGCAAATTTAAAGTTGAACTAAGATTCTA
TCTTGGACAACCAGCTATCACCAGGCTCGGTAGGTTTGTCGCCTCTACCT
ATAAATCTTCCCACTATTTTGCTACATAGACGGGTGTGCTCTTTTAGCTG
TTCTTAGGTAGCTCGTCTGGTTTCGGGGGTCTTAGCTTTGGCTCTCCTTG
CAAAGTTATTTCTAGTTAATTCATTATGCAGAAGGTATAGGGGTTAGTCC
TTGCTATATTATGCTTGGTTATAATTTTTCATCTTTCCCTTGCGGTACTA
TATCTATTGCGCCAGGTTTCAATTTCTATCGCCTATACTTTATTTGGGTA
AATGGTTTGGCTAAGGTTGTCTGGTAGTAAGGTGGAGTGGGTTTGGGGCT
GTTCGTCCAAGTGCACTTTCCAGTACACTTACCATGTTACGACTTGTCTC
CTCTATATAAATGCGTAGGGGTTTTAGTTAAATGTCCTTTGAAGTATACT
TGAGGAGGGTGACGGGCGGTGTGTACGCGCTTCAGGGCCCTGTTCAACTA
AGCACTCTACTCTTAGTTTACTGCTAAATCCACCTTCGACCCTTAAGTTT
CATAAGGGCTATCGTAGTTTTCTGGGGTAGAAAATGTAGCCCATTTCTTG
CCACCTCATGGGCTACACCTTGACCTAACGTCTTTACGTGGGTACTTGCG
CTTACTTTGTAGCCTTCATCAGGGTTTGCTGAAGATGGCGGTATATAGGC
TGAGCAAGAGGTGGTGAGGTTGATCGGGGTTTATCGATTACAGAACAGGC
TCCTCTAGAGGGATATGAAGCACCGCCAGGTCCTTTGAGTTTTAAGCTGT
GGCTCGTAGTGTTCTGGCGAGCAGTTTTGTTGATTTAACTGTTGAGGTTT
AGGGCTAAGCATAGTGGGGTATCTAATCCCAGTTTGGGTCTTAGCTATTG
TGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGTCAACTG
GAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGAT
CTAAAACACTCTTTACGCCGGCTTCTATTGACTTGGGTTAATCGTGTGAC
CGCGGTGGCTGGCACGAAATTGACCAACCCTGGGGTTAGTATAGCTTAGT
TAAACTTTCGTTTATTGCTAAAGGTTAATCACTGCTGTTTCCCGTGGG
TGTGGCTAGGCTAAGCGTTTTGAGCTGCATTGCTGCGTGCTTGATGCTTG
TTCCTTTTGATCGTGGTGATTTAGAGGGTGAACTCACTGGAACGGGGATG
CTTGCATGTGTAATCTTACTAAGAGCTAATAGAAAGGCTAGGACCAAACC
AAAGCCTACAGCACCCGGTATTCCCAGGCGGTCTCCCATCCAAGTACTAA
CCAGGCCCGACCCTGCTTAGCTTCCGAGATCAGACGAGATCGGGCGCGTT
TTCCGAGATCAGACGAGATCGGGCGCGTTCAGGGTGGTATGGCCGTAGAC
""".strip().split()
