from collections import namedtuple
import os

CampareeConstants = namedtuple('Constants',
                               ['CAMPAREE_DIR',
                                'DEFAULT_STAR_OUTPUT_PREFIX',
                                'DEFAULT_STAR_BAM_FILENAME',
                                'INTRON_OUTPUT_FILENAME',
                                'INTRON_OUTPUT_ANTISENSE_FILENAME',
                                'INTERGENIC_OUTPUT_FILENAME',
                                'VARIANTS_FINDER_OUTPUT_FILENAME',
                                'VARIANTS_FINDER_LOG_FILENAME',
                                'VARIANTS_COMPILATION_OUTPUT_FILENAME',
                                'VARIANTS_COMPILATION_LOG_FILENAME',
                                'BEAGLE_OUTPUT_PREFIX',
                                'BEAGLE_OUTPUT_FILENAME',
                                'BEAGLE_LOG_FILENAME',
                                'GENOMEBUILDER_OUTPUT_PREFIX',
                                'GENOMEBUILDER_SEQUENCE_FILENAME_PATTERN',
                                'GENOMEBUILDER_OUTPUT_PREFIX',
                                'GENOMEBUILDER_SEQUENCE_FILENAME_PATTERN',
                                'GENOMEBUILDER_INDEL_FILENAME_PATTERN',
                                'GENOMEBUILDER_MAPPER_FILENAME_PATTERN',
                                'GENOMEBUILDER_LOG_FILENAME',
                                'UPDATEANNOT_OUTPUT_FILENAME_PATTERN',
                                'UPDATEANNOT_LOG_FILENAME_PATTERN',
                                'TRANSCRIPTOMES_LOG_FILENAME'])

CampareeConstants.__doc__ = """
Provides a list of constants specific to the CAMPAREE pipeline.
These include input/output/logging filenames used by various
steps in the pipeline.
"""

_CAMPAREE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_DEFAULT_STAR_OUTPUT_PREFIX="genome_alignment."
CAMPAREE_CONSTANTS = \
    CampareeConstants(CAMPAREE_DIR=_CAMPAREE_DIR,
                      DEFAULT_STAR_OUTPUT_PREFIX=_DEFAULT_STAR_OUTPUT_PREFIX,
                      DEFAULT_STAR_BAM_FILENAME=f"{_DEFAULT_STAR_OUTPUT_PREFIX}Aligned.sortedByCoord.out.bam",
                      INTRON_OUTPUT_FILENAME="intron_quantifications.txt",
                      INTRON_OUTPUT_ANTISENSE_FILENAME="intron_antisense_quantifications.txt",
                      INTERGENIC_OUTPUT_FILENAME="intergenic_quantifications.txt",
                      VARIANTS_FINDER_OUTPUT_FILENAME="variants.txt",
                      VARIANTS_FINDER_LOG_FILENAME="VariantsFinderStep.log",
                      VARIANTS_COMPILATION_OUTPUT_FILENAME="all_variants.vcf",
                      VARIANTS_COMPILATION_LOG_FILENAME="VariantsCompilationStep.log",
                      BEAGLE_OUTPUT_PREFIX="beagle",
                      BEAGLE_OUTPUT_FILENAME="beagle.vcf.gz",
                      BEAGLE_LOG_FILENAME="BeagleStep.log",
                      #Prefix for names of all (non-log) files generated by GenomeBuilderStep
                      GENOMEBUILDER_OUTPUT_PREFIX="custom_genome",
                      #String pattern to construct sequence FASTA filename generated by GenomeBuilderStep.
                      GENOMEBUILDER_SEQUENCE_FILENAME_PATTERN='{genome_output_file_stem}_{genome_name}.fa',
                      #String pattern to construct indel filename generated by GenomeBuilderStep
                      GENOMEBUILDER_INDEL_FILENAME_PATTERN='{genomebuilder_output_prefix}_indels_{genome_name}.txt',
                      #String pattern to construct reference mapping filename generated by GenomeBuilderStep
                      GENOMEBUILDER_MAPPER_FILENAME_PATTERN='{genome_output_file_stem}_to_parental_coordinate_mapping_{genome_name}.txt',
                      #Name of file where GenomeBuilderStep logging is stored
                      GENOMEBUILDER_LOG_FILENAME="GenomeBuilderStep.log",
                      #Name of updated annotation file generated UpdateAnnotationForGenomeStep.
                      UPDATEANNOT_OUTPUT_FILENAME_PATTERN='updated_annotation_{genome_name}.txt',
                      #Name of file where UpdateAnnotationForGenomeStep logging is stored
                      UPDATEANNOT_LOG_FILENAME_PATTERN='UpdateAnnotationForGenomeStep_{genome_name}.log',
                      TRANSCRIPTOMES_LOG_FILENAME="TranscriptQuantificatAndMoleculeGenerationStep.log"
                     )
